language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: enW7ulVAhzF0jKp5r33qKfNEwy6m4/0gt4v5ByDmiG3mmnS01YXPd44AQE6m0ln659pfn9lgtb5H2URykhTkVKkS1jld763hSyGOybgp1hrT8CWv/+lm5lZh569e13h/OhSgiP3pZpAPFutwME8826ZVTa6HlbYX9M1kB1+s6Dj5wjPxpf5ZJvmcYemIz8P9ku+pWWSBcaRWZdoUNOr3ZC15XksypLxTvF+RIDHQQcvv5fndbLvre4LbG1MqKeiy4EYSMZEF6FDgM3FRejVitSMHXoeXW5O7OqFzbHUqVMKHAYajsCzI6qcKPgrIdKk/jSAK0G5iIPWsXKaiBU9VI4bUJjmqW+BWOYCNGtKeH/LEMRSa6IvT95flrbWEeq3jDVW1DLslrD19l2Z2T3TzHnWje0k1SmweG/GfN45jDdeNbtx1X9+sNRSh7p/nA0PP0GuCdanfYTsgIfdvslJc8MxyiRNohCVcBGr2TdXp8wljdhKdN6iITOc8prjKO5qXfFZGPOcmD1tPf+4Ow43AOSI6LN61MCHFALjdPsPQVbXYBs3sN2TbfpyH1xjXKa/Vk8lCsG0PWj+9BT8mWRxH5OTLa5TqYtmfnrd2seR4niQ9/vXmpkWz+31gUwQS4xfR78gTglp9PWW4CgEQuA8AP+02L45NNs5tOydkX2YZ3e0=
  app: pacific-headland-97222
  on:
    repo: richigro/Simple-Blog-Api
